/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:c8511af555236f49de0e70dd9a7f330e:3c93535e0166175ddb3b77b748639f98:9372a5c6e87557cd082219126b413cbe$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class sprites
	{
		public const string Biplane_body = "biplane/body";
		public const string Biplane_crate = "biplane/crate";
		public const string Biplane_propeller_1 = "biplane/propeller/1";
		public const string Biplane_propeller_2 = "biplane/propeller/2";
		public const string Biplane_propeller_3 = "biplane/propeller/3";
		public const string Bomber_body = "bomber/body";
		public const string Bomber_bomb = "bomber/bomb";
		public const string Bomber_explosion_1 = "bomber/explosion/1";
		public const string Bomber_explosion_2 = "bomber/explosion/2";
		public const string Bomber_explosion_3 = "bomber/explosion/3";
		public const string Bomber_explosion_4 = "bomber/explosion/4";
		public const string Bomber_explosion_5 = "bomber/explosion/5";
		public const string Bomber_explosion_6 = "bomber/explosion/6";
		public const string Bomber_explosion_7 = "bomber/explosion/7";
		public const string Bomber_explosion_8 = "bomber/explosion/8";
		public const string Bomber_propeller_1 = "bomber/propeller/1";
		public const string Bomber_propeller_2 = "bomber/propeller/2";
		public const string Bomber_propeller_3 = "bomber/propeller/3";
		public const string Bomber_propeller_4 = "bomber/propeller/4";
		public const string Hp_bar = "hp/bar";
		public const string Hp_pip = "hp/pip";
		public const string Jeep_arm = "jeep/arm";
		public const string Jeep_body_1 = "jeep/body/1";
		public const string Jeep_body_2 = "jeep/body/2";
		public const string Jeep_body_3 = "jeep/body/3";
		public const string Jeep_body_4 = "jeep/body/4";
		public const string Jeep_body_5 = "jeep/body/5";
		public const string Jeep_body_6 = "jeep/body/6";
		public const string Jeep_death_1 = "jeep/death/1";
		public const string Jeep_death_2 = "jeep/death/2";
		public const string Jeep_death_3 = "jeep/death/3";
		public const string Jeep_death_4 = "jeep/death/4";
		public const string Jeep_death_5 = "jeep/death/5";
		public const string Jeep_death_6 = "jeep/death/6";
		public const string Jeep_death_7 = "jeep/death/7";
		public const string Jeep_death_8 = "jeep/death/8";
		public const string Jeep_death_9 = "jeep/death/9";
		public const string Jeep_driver = "jeep/driver";
		public const string Jeep_explosion_1 = "jeep/explosion/1";
		public const string Jeep_explosion_2 = "jeep/explosion/2";
		public const string Jeep_explosion_3 = "jeep/explosion/3";
		public const string Jeep_explosion_4 = "jeep/explosion/4";
		public const string Jeep_explosion_5 = "jeep/explosion/5";
		public const string Jeep_explosion_6 = "jeep/explosion/6";
		public const string Jeep_explosion_7 = "jeep/explosion/7";
		public const string Jeep_explosion_8 = "jeep/explosion/8";
		public const string Jeep_grenade = "jeep/grenade";
		public const string Jeep_grenadier = "jeep/grenadier";
		public const string Panther_body_1 = "panther/body/1";
		public const string Panther_body_2 = "panther/body/2";
		public const string Panther_body_3 = "panther/body/3";
		public const string Panther_body_4 = "panther/body/4";
		public const string Panther_cannon_1 = "panther/cannon/1";
		public const string Panther_cannon_2 = "panther/cannon/2";
		public const string Panther_cannon_3 = "panther/cannon/3";
		public const string Panther_cannon_4 = "panther/cannon/4";
		public const string Panther_death_1 = "panther/death/1";
		public const string Panther_death_10 = "panther/death/10";
		public const string Panther_death_11 = "panther/death/11";
		public const string Panther_death_12 = "panther/death/12";
		public const string Panther_death_13 = "panther/death/13";
		public const string Panther_death_14 = "panther/death/14";
		public const string Panther_death_2 = "panther/death/2";
		public const string Panther_death_3 = "panther/death/3";
		public const string Panther_death_4 = "panther/death/4";
		public const string Panther_death_5 = "panther/death/5";
		public const string Panther_death_6 = "panther/death/6";
		public const string Panther_death_7 = "panther/death/7";
		public const string Panther_death_8 = "panther/death/8";
		public const string Panther_death_9 = "panther/death/9";
		public const string Panther_shell = "panther/shell";
		public const string Player_body_1 = "player/body/1";
		public const string Player_body_2 = "player/body/2";
		public const string Player_body_3 = "player/body/3";
		public const string Player_body_4 = "player/body/4";
		public const string Player_body_5 = "player/body/5";
		public const string Player_body_6 = "player/body/6";
		public const string Player_cannon_1 = "player/cannon/1";
		public const string Player_cannon_2 = "player/cannon/2";
		public const string Player_cannon_3 = "player/cannon/3";
		public const string Player_cannon_4 = "player/cannon/4";
		public const string Player_death_1 = "player/death/1";
		public const string Player_death_10 = "player/death/10";
		public const string Player_death_11 = "player/death/11";
		public const string Player_death_12 = "player/death/12";
		public const string Player_death_13 = "player/death/13";
		public const string Player_death_14 = "player/death/14";
		public const string Player_death_15 = "player/death/15";
		public const string Player_death_16 = "player/death/16";
		public const string Player_death_17 = "player/death/17";
		public const string Player_death_18 = "player/death/18";
		public const string Player_death_19 = "player/death/19";
		public const string Player_death_2 = "player/death/2";
		public const string Player_death_20 = "player/death/20";
		public const string Player_death_3 = "player/death/3";
		public const string Player_death_4 = "player/death/4";
		public const string Player_death_5 = "player/death/5";
		public const string Player_death_6 = "player/death/6";
		public const string Player_death_7 = "player/death/7";
		public const string Player_death_8 = "player/death/8";
		public const string Player_death_9 = "player/death/9";
		public const string Player_shell = "player/shell";
	}
}